siteTitle = "Ihor Orlovskyi Portfolio"
siteDescr = "Web Scientist, Front-end Engineer & Psychedelic Musician"
siteAuthor = "Ihor Orlovskyi"

siteLinkedinUrl = "https://www.linkedin.com/in/ihororlovskyi"
siteFbUrl = "https://www.facebook.com/ihororlovskyi"
siteGithubUrl = "https://github.com/ihororlovskyi"
siteSoundcloudUrl = "https://soundcloud.com/irukanji-music"
siteInstagramUrl = "https://instagram.com/ihororlovskyi"
siteGpUrl = "https://plus.google.com/104535536639391603666"
siteTwitterUrl = "https://twitter.com/ihororlovskyi"


linkPrefix = "/react-porfolio"
