siteTitle = "Ihor Orlovskyi Portfolio"
siteDescr = "Web Scientist, Front-end Engineer & Psychedelic Musician"
siteAuthor = "Ihor Orlovskyi"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "https://github.com/ihororlovskyi"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"
siteFb = "https://www.facebook.com/ihororlovskyi"

linkPrefix = "/porfolio-on-gatsby"
